#
# Vivado (TM) v2017.1 (64-bit)
#
# Project_Vidado.tcl: Tcl script for re-creating project 'project_3'
#
# Generated by Vivado on Mon Nov 23 11:30:03 EST 2020
# IP Build 1846188 on Fri Apr 14 20:52:08 MDT 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
#    "/import/home/tsung/CODE/Virtex7_Vivado/project_3/project_1.srcs/sources_1/imports/CODE/Virtex7_Vivado/build-00000/constants_pkg.vhd"
#    "/import/home/tsung/CODE/Virtex7_Vivado/io_wrapper.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."
set git_dir "/import/home/tsung/CODE/cift-internal"

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "Project_Vidado.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}


if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/project_3"]"

# Create project
create_project project_3 ./project_3 -part xc7k70tfbg484-3

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects project_3]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/project_3.cache/ip" -objects $obj
set_property -name "part" -value "xc7k70tfbg484-3" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "DisplayOnly" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# "[file normalize "$origin_dir/project_3/import_xst_summary.txt"]"\
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/SRC/constants_pkg.vhd"]"\
 "[file normalize "$origin_dir/SRC/gold.vhd"]"\
 "[file normalize "$git_dir/builders_repo/architectures/xilinx/hdl/lut_test_tpg_8_3-1.vhd"]"\
 "[file normalize "$git_dir/code/main/ift/builders/plbs/hdl/ora.vhd"]"\
 "[file normalize "$origin_dir/SRC/test_gen.vhd"]"\
 "[file normalize "$git_dir/code/main/ift/builders/plbs/hdl/capture_small.vhd"]"\
 "[file normalize "$git_dir/code/main/ift/builders/plbs/hdl/harness.vhd"]"\
 "[file normalize "$git_dir/interfaces/bscan_series7/io_wrapper_50MHz.vhd"]"\
 "[file normalize "$origin_dir/SRC/plb.vhd"]"\
 "[file normalize "$git_dir/builders_repo/architectures/xilinx/series7/hdl/series7_slicel.vhd"]"\
 "[file normalize "$origin_dir/SRC/constants_pkg.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/SRC/constants_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/SRC/gold.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$git_dir/builders_repo/architectures/xilinx/hdl/lut_test_tpg_8_3-1.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$git_dir/code/main/ift/builders/plbs/hdl/ora.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/SRC/test_gen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj


set file "$git_dir/code/main/ift/builders/plbs/hdl/capture_small.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$git_dir/code/main/ift/builders/plbs/hdl/harness.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$git_dir/interfaces/bscan_series7/io_wrapper_50MHz.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/SRC/plb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$git_dir/builders_repo/architectures/xilinx/series7/hdl/series7_slicel.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SRC/constants_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "top_level" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/io_wrapper.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/io_wrapper.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k70tfbg484-3 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7k70tfbg484-3" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]


# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k70tfbg484-3 -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7k70tfbg484-3" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:project_3"

synth_design -rtl -name rtl_1

launch_runs synth_1 -jobs 20
wait_on_run synth_1


#open_run rtl_1 -name rtl_1
#start_group
#end_group
open_run synth_1 -name synth_1
foreach h_slice [list SLICE_X1Y0 SLICE_X1Y1 SLICE_X1Y2 SLICE_X1Y3 SLICE_X1Y4 SLICE_X1Y5] {
    create_pblock pblock_$h_slice
    resize_pblock pblock_$h_slice -add $h_slice:$h_slice
}
foreach h_slice [list SLICE_X1Y0 SLICE_X1Y1 SLICE_X1Y2 SLICE_X1Y3 SLICE_X1Y4 SLICE_X1Y5] {
    add_cells_to_pblock pblock_$h_slice [get_cells harness/test_region_i/$h_slice]
}

launch_runs impl_1 -jobs 20
wait_on_run impl_1

#write_verilog -mode funcsim -include_xilinx_libs -force luts1_post.v


