#!/bin/bash -x
docker run \
           -v /export/tools/synopsys/vcs:/projects/vcs \
           -v /export/tools/synopsys/vc_static:/projects/vc_static \
-itd chipyard_base bash
#           -v /projects:/projects \
#
# install gcc 4.8.5
# apt install make wget git gcc g++ lhasa libgmp-dev libmpfr-dev libmpc-dev flex bison gettext texinfo ncurses-dev autoconf rsync

