#!/bin/bash
. /export/tools/xilinx/14.7/ISE_DS/settings64.sh
#
#
# vivado -mode gui 
# vivado -mode tcl
# vivado -mode batch -source Your_SCRIPT.tcl
# link_design -part xc7s25csga324-1
# link_design -part xc7s100fgga676-1
# link_design -part xczu3eg-sfva625-1-e
# --- trouble to part is not specified !!!
# open_checkpoint $prj_out/_ROUTED.dcp
#
#cd /import/home/tsung/CODE/SP7_planA/1-mux1/build-00000
#rm -rf mux1_prj
#rm -rf project_3
#vivado -mode gui
#planAhead &
planAhead -mode batch -source bram_planA.tcl
