#! /bin/bash
# run board on Spartan7 - use sp7_board_harness.py
# specify how hardware configured and it's bit stream file
# debug the error message in the vivado_lab.log file -- check error message
#
. /nas/projects/cift/tysung/TEST_Q7/cift-internal/installations/full/python/bin/activate
python3 sp7_board_harness.py
deactivate

